### ISSUE TITLE
Surds comparison

### ISSUE THREAD

**Issue by ieshaan12** [lukew3/mathgenerator#104]
Example: cuberoot(25) and squareroot(37).
Solution: cuberoot(25) < squareroot(37).

Ranges: Values from 0 to 100
Roots: 2 to 10

Assign this to me if this is fine.

**Comment by lukew3** [comment]
The question and solution is kind of unclear. It could be something like: "Which operator describes the relationship between cuberoot(25) and squareroot(37)" and the solution could just be "<".
