### ISSUE TITLE
Possible solutions of a family of linear equations having three variables.

### ISSUE THREAD

**Issue by SunTzunami** [lukew3/mathgenerator#121]
Linear equations having three variables can be solved if at least three such equations are available.
for example, given the three equations- x+2z=9, 2y+z=8 and 4x-3y=-2.
By using Cramer's rule one can solve the set of equations to obtain x=1, y=2 and z=4.
I would like to implement it via code- I'd generate three equations and solve for the three unknown variables.
I'd be grateful if you could assign the issue to me if you deem it worthy.
On a side note, I would like to point out that the function for "Fourth angle of a quadrilateral, given three other angles" generates angles for only convex quadrilaterals (quadrilateral whose interior angles do not exceed 180°) and not for concave quadrilaterals (quadrilateral for which one angle exceeds 180°).

**Comment by lukew3** [comment]
This looks like the same thing as the linearEquationsFunc found on line 385. If you run `linearEquations(n=3)` you get something like this:
```
15x + 11y + 3z = -110
18x + 13y + 9z = -64
-16x + -11y + 4z = 219

x = -18, y = 11, z = 13
```

As for the fourth angle function, if you can fix that in a pull request that would be great.

**Comment by SunTzunami** [comment]
Sounds like a plan. 
I'll try fixing the fourth angle.
