### ISSUE TITLE
Matrix  Invertion

### ISSUE THREAD

**Issue by Gourav2000** [lukew3/mathgenerator#125]
Generate a random invertible matrix compute it's inverse and display the output. If it's available I would like for it to be assigned to me. Thanks in advance.

**Comment by SunTzunami** [comment]
Good idea but remember to check that if it's invertible first. Do specify which order matrix are you gonna find the inverse for (2x2 or 3x3 or 4x4 etc.)

**Comment by Gourav2000** [comment]
> Good idea but remember to check that if it's invertible first. Do specify which order matrix are you gonna find the inverse for (2x2 or 3x3 or 4x4 etc.)

Sure
