### ISSUE TITLE
Probability of getting a sum on n dices

### ISSUE THREAD

**Issue by Ritu1611** [lukew3/mathgenerator#126]
Suppose you rolled **a** dices at a time and you want to get probability of **b** as a sum of all face values.

Example= I rolled 3 dices at a time. I want to know the probability of 15 as a sum.
Solution= Probability is 10/216
@lukew3

**Comment by pranjalyadav451** [comment]
Can I work on this issue ?

**Comment by Ritu1611** [comment]
@pranjalyadav451  This is already done. But you can still work on probability problems with inclusion of boxes and drawing of different coloured balls.
