### ISSUE TITLE
Fix useless parameters

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#14]
Some functions have parameters that don't do what they are supposed to. These need to be fixed before next release.

**Comment by mushahidq** [comment]
Can you provide an example? I am looking to contribute.

**Comment by lukew3** [comment]
@mushahidq In multiplicationFunc the parameter maxRes should restrict the value of c so that it is not higher than maxRes. However, this is not the case as the max value of variable b is too high. Look at additionFunc and subtractionFunc to see what the parameters should do. DivisionFunc and moduloFunc don't need maxRes parameters because c will always be smaller than maxDivid or maxModulo.

**Comment by mushahidq** [comment]
I understand what the problem. I hope its alright if I use a for loop. I think a better solution would be to have all the factors stored in an array and then generate a random number with highest being the last index of the array. The problem elements would be the element stored at that position and the  quotient of its division with the solution which was generated first. Is it alright if I implement this?

**Comment by mushahidq** [comment]
I have made a PR with a fix.
