### ISSUE TITLE
Arithmetic Progression

### ISSUE THREAD

**Issue by anshitabaid** [lukew3/mathgenerator#143]
Function to calculate either sum of given AP or the n'th term of the AP
Eg:

Find the 5th term of the AP series : 2, 4, 6, ....
or
Find the sum of first 10 terms of the AP series 2, 4, 6 ...

**Comment by Harshal0902** [comment]
Can I work on this issue?

**Comment by rohitsingh2410** [comment]
Hi can you please assign it to me?
