### ISSUE TITLE
Data Mean and Standard Deviation

### ISSUE THREAD

**Issue by NarayanAdithya** [lukew3/mathgenerator#148]
Problem : Given a list of numbers find its mean, standard deviation and variance ,

example : 1,2,3,4,5,6,7,8,9,10

Solution : Mean - 5.5 , Standard Deviation - 2.87 , Variance - 8.25

**Comment by Harshal0902** [comment]
Can I work on this Isue?

**Comment by NarayanAdithya** [comment]
I wanted to work on this issue, i am new to these contributions

**Comment by NarayanAdithya** [comment]
Should i wait for the owner of the repo to add the hacktoberfest label and then make the pull request? or just do it now ?

**Comment by NarayanAdithya** [comment]
Please Assign me this task.
