### ISSUE TITLE
Geometric Progression

### ISSUE THREAD

**Issue by NarayanAdithya** [lukew3/mathgenerator#150]
Problem : Given the series 3,6,12,24,48,96 find the 7th element , common ratio, sum till 3rd term

Solution : 7th Element of GP : 192 , Common Ratio : 2 , Sum till 3rd term : 20

**Comment by sleepy0owl** [comment]
want to work on this

**Comment by NarayanAdithya** [comment]
Hey I am new to this , So should we be waiting to add the hacktoberfest label and then make a pull request?

**Comment by NarayanAdithya** [comment]
Please assign me this task.

**Comment by NarayanAdithya** [comment]
solved in pull request #175
