### ISSUE TITLE
Differentiation

### ISSUE THREAD

**Issue by strikeraryu** [lukew3/mathgenerator#151]
I want to work on a generator for differentiation problems (allow the user to choose different complexity)
problem eg:   log(x^2)
solution: 2/x or (2x)/(x^2)

**Comment by strikeraryu** [comment]
I am working on this so I like to get assigned to this.
Thanks.

**Comment by strikeraryu** [comment]
Hey, can we use external libraries?  @lukew3

**Comment by lukew3** [comment]
Yes, that's fine.
