### ISSUE TITLE
Linter Failing

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#173]
Last 4 lines of linter details look like this:
```
./mathgenerator/mathgen.py:988:100: E231 missing whitespace after ','
make: *** [lint] Error 1
Makefile:4: recipe for target 'lint' failed
Error: Process completed with exit code 2.
```
218 lines above that that say something similar to the first line mentioned above. Mention missing whitespace and expecting blank lines.

**Comment by lukew3** [comment]
@YuviGold You might be able to fix this.

**Comment by NarayanAdithya** [comment]
Hey i checked up the errors, most of them are related to not spacing the variables after ',' and space around operators.

**Comment by vishnudk** [comment]
the issue is not  solved yet , spacing the variables after ',' and space around operators didn't made much of a change

**Comment by YuviGold** [comment]
@lukew3 I created a PR solving the current issues.

I added a `format` target so contributors would be able to use `make format`. It is supposed to fix the small linting errors.

**Comment by vishnudk** [comment]
actually i am new to git , like can you exaplain how to use it

**Comment by vishnudk** [comment]
should just create a pr
