### ISSUE TITLE
Base Conversion

### ISSUE THREAD

**Issue by AceVikings** [lukew3/mathgenerator#190]
**Example Problem:**
Convert '10' from base 2 to base 10 
**Example Solution:**
2
**Further explanation:**
Questions will ask user to convert a particular number from a given base to a given base
**Would you like to be assigned to this:**
Yes

**Comment by Dvd1234** [comment]
Can I try this out?

**Comment by GursimranHeer** [comment]
I would like to be assigned to this.

**Comment by GursimranHeer** [comment]
Hey, I've put together a concise solution to this problem. Can you please assign me this?
