### ISSUE TITLE
Hypotenuse length Finder

### ISSUE THREAD

**Issue by rajkumawat01** [lukew3/mathgenerator#193]
**Example Problem:**- Find the length of the hypotenuse when sides forming right angles are provided.

**Example Solution:**-
Input:
    Side 1 = 3
    Side 2 = 4

Output:
    Hypotenuse = 5

**Further explanation:**
Uses the Pythagoras theorem to find Hypotenuse

**Would you like to be assigned to this:**
Please would you assign this to me

**Comment by rajkumawat01** [comment]
Please assign this function to me

**Comment by luckythandel** [comment]
I am here to solve this issue as fast as I can. Assign to me, please.

**Comment by lukew3** [comment]
We already have this. pythagoreanTheorem() id 25.
