### ISSUE TITLE
Division(whole number quotient)

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#2]
Example Problem:
8/2=
Example Solution:
4

**Comment by the-lightstack** [comment]
I will add simple Divisions (with the solution being an integer) and normal division were the solution can also be a floating point number.

**Comment by lukew3** [comment]
@bottleInALightning I like that. Somebody already filled the floating point generator but the integer division would be much better for elementary students and such that haven't learned decimals.

**Comment by lukew3** [comment]
This issue is still open. Create a seperate class instance/function where the solution of the division problem must be an integer, not a decimal. You can call it divisionIntSolution.

**Comment by the-lightstack** [comment]
Ok Im doing it
