### ISSUE TITLE
Bubble sort algorithm

### ISSUE THREAD

**Issue by arpitg24** [lukew3/mathgenerator#200]
**Example Problem:**
given an array of n integers: [4, 2, 5, 6, 8], we sort it using the bubble sort sorting algorithm
**Example Solution:**
The expected output for above array will be a sorted array: [2, 4, 5, 6, 8]
**Further explanation:**
We use the bubble sort algorithm which repeatedly traverses the array and swaps integers based on their magnitude to sort the whole array.
**Would you like to be assigned to this:**
yes

**Comment by AHA2006** [comment]
Hello @arpitg24, May I work on this?

**Comment by baycak** [comment]
Hi, I'd like to work on this issue

**Comment by AHA2006** [comment]
Hello, I send a pull request for this issue

**Comment by lukew3** [comment]
This is not what this repository is for.
