### ISSUE TITLE
2's complement of a Binary number

### ISSUE THREAD

**Issue by devansh-07** [lukew3/mathgenerator#203]
**Example Problem:** Find 2's complement of 11010110.

**Example Solution:** 101010

**Further explanation:** A function to find the 2's complement of a binary number.

**Would you like to be assigned to this:** Yes, Could you please assign this to me?

**Comment by bhargav28** [comment]
yes , could you please assign this to me?

**Comment by Metropass** [comment]
@devansh-07 I would like to be assigned this task

**Comment by devansh-07** [comment]
@Metropass, I want this issue to be assigned to me and that's why I've opened it. You should open a new issue for a new problem.

**Comment by Metropass** [comment]
i see, thanks for the clarification!
