### ISSUE TITLE
Calculate area of sector

### ISSUE THREAD

**Issue by abhijitpal1247** [lukew3/mathgenerator#204]
**Example Problem:**  Given radius, 4 and angle, 45. Find the area of the sector.
**Example Solution:**  Area of sector = (angle / 360) * π*r^2 . 
area of given sector = (45/360) * π*4^2 = 6.2857

**Further explanation:** A circular sector, is the portion of a disk enclosed by two radii and an arc.
**Would you like to be assigned to this:** Yes

**Comment by bhargav28** [comment]
Hey ! i would like to take this

**Comment by tapish2000** [comment]
I would like to work on this. Can you assign this issue to me?

**Comment by tiara1** [comment]
I would like to take this up.

**Comment by shyamcody** [comment]
assign
