### ISSUE TITLE
Calculate arc length of the given angle

### ISSUE THREAD

**Issue by abhijitpal1247** [lukew3/mathgenerator#205]
**Example Problem:** Given the radius of the circle, 4 and angle, 45. Calculate the arc length of the given angle. 

**Example Solution:** Arc length = (angle/360) * 2*π*r
arc length = (45/360) * 2*π*4 = 3.14285

**Further explanation:** The arc length of an angle is the distance along the curve which makes the given angle.

**Would you like to be assigned to this:** Yes

**Comment by shivambachhety** [comment]
Yes,I can do this.
