### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by Metropass** [lukew3/mathgenerator#209]
**Example Problem:**
Sorting an unordered list
**Example Solution:**
`quicksort(list, start, end)`
**Further explanation:**
A quicksort function that sorts numbers from index 0 to list-1
**Would you like to be assigned to this:**
Yes, I would like to be assigned this

**Comment by TestPrab** [comment]
@Metropass Hi, can you please assign me this?  I would like to work on it

**Comment by Metropass** [comment]
> @Metropass Hi, can you please assign me this? I would like to work on it
Unfortunatlely, this task if for me. You can create a new issue on an idea of your choice

**Comment by Swayam221** [comment]
@lukew3 is this kind of problem acceptable for this project? this issue states a programming algorithm and not a mathematics question i think.

**Comment by Metropass** [comment]
I can edit the function to print out the list as it's being sorted
