### ISSUE TITLE
Faro Shuffle of List

### ISSUE THREAD

**Issue by Metropass** [lukew3/mathgenerator#214]
**Example Problem:**
Riffle cutting the List, List must be even. Also allows the user to do a inner shuffle, or an outer shuffle
**Example Solution:**
`faro_shuffle(list, True)`, where the second argument indicates if you want to commit to an outer shuffle
**Further explanation:**
The faro shuffle method of shuffling the list slices the data structure into two halfs, and then the two halves of list are merged back together
**Would you like to be assigned to this:**
Yes, I would like to be assigned this

**Comment by GursimranHeer** [comment]
I would like to be assigned this.

**Comment by Metropass** [comment]
> I would like to be assigned this.

Unfortunately I'm already in the midst of coding this, you're gonna have to make a new issue for your idea

**Comment by GursimranHeer** [comment]
Okay

**Comment by lukew3** [comment]
This isn't what this repository is for.

**Comment by Metropass** [comment]
@lukew3 Sorry. I now understand what to do. I had an idea on Calkin-Wilf's sequence, would that be okay for an Issue?

**Comment by lukew3** [comment]
This repository is for generating math problems for students to solve. Your implementations seem to be focused on implementing computer science functions. This is not what this repository is for. Read over CONTRIBUTING.md and the mathgen.py file if you want to see what should be created in this repository.

**Comment by Metropass** [comment]
I see now. Would something like solving the minimum number of blocks in a pyramid be an okay issue? I know that's a math heavy problem @lukew3 

I'm sorry for all the spam 😞
