### ISSUE TITLE
2x2 matrix determinant

### ISSUE THREAD

**Issue by Riei-Joaquim** [lukew3/mathgenerator#215]
**Example Problem:**
Given that a is the matrix 2x2 A =[[{2}, {5}], [{1}, {7}]] , calculate the determinant.

**Example Solution:**
Being A= [[{a}, {b}], [{c}, {d}]], having to Det(A) = a * d - b * c, Det(A) = 9
**Further explanation:**

**Would you like to be assigned to this:**
Yes

**Comment by satyamkoshta340** [comment]
can you assign this problem to me? I would like to solve this problem in python. And Det(A) should be 9 or 19?

**Comment by Riei-Joaquim** [comment]
Thanks for the fix of the calculation in the issue.
@satyamkoshta340 Cool that you are interested, but I created this issue because I want to be assigned to this activity, you can open new issues for other mathematical problems.

**Comment by satyamkoshta340** [comment]
where would I get these problems ?

**Comment by Riei-Joaquim** [comment]
@satyamkoshta340 As the purpose of this repository is to support mathematics studies, I suggest looking for common math problems at school.

**Comment by satyamkoshta340** [comment]
thanks, I got it!
