### ISSUE TITLE
isprime number

### ISSUE THREAD

**Issue by satyamkoshta340** [lukew3/mathgenerator#221]
**Example Problem:** Check weather given number A is prime or not.

**Example Solution:** let A = 15 return False, if A = 7 return True

**Further explanation:** check weather number is prime or not

**Would you like to be assigned to this:** Yes , I will love to solve this problem!

**Comment by lukew3** [comment]
Good one!

**Comment by satyamkoshta340** [comment]
#228

**Comment by prerna250** [comment]
Can you please assign me this? I'll do it in python

**Comment by satyamkoshta340** [comment]
@prerna250 I want to work on this problem that's why I open it , You can create your new issue.

**Comment by prerna250** [comment]
okk

**Comment by DaRkSouL-1** [comment]
assign me plz

**Comment by satyamkoshta340** [comment]
Added solution #228
