### ISSUE TITLE
Set Theory, Union,Intersection,Difference,Symmetric Difference

### ISSUE THREAD

**Issue by NarayanAdithya** [lukew3/mathgenerator#227]
**Example Problem:**
Given the two set : {1,2,4} , {1,2}  find the union,intersection,difference and symmetric difference of the two sets.
**Example Solution:**
Union : {1,2,4}
Intersection : {1,2}
Difference : {4}
Sym Difference : {4}
**Further explanation:**

**Would you like to be assigned to this:**
I request you to assign me this task.

**Comment by GursimranHeer** [comment]
Can I please be assigned this?

**Comment by NarayanAdithya** [comment]
I opened the issue with the intention to work on this issue.

**Comment by GursimranHeer** [comment]
Okay. I got confused because of:
"**Would you like to be assigned to this:**
I request you to assign me this task.".
