### ISSUE TITLE
Curved Surface Area of cylinder

### ISSUE THREAD

**Issue by RohanTheProgrammer** [lukew3/mathgenerator#230]
CSA of a cylinder whose Height = 7m and radius = 1m

CSA of the Cylinder is 44m^2

This Curved Surface Area generator will take length and radius of the cylinder as inputs and the n calculate and outputs the curved survace area of the cylinder which is derived by the following formula:
2*pie*r*h

I would love to be assigned for this project and please react to this as soon as possible because it is going to be counted in Hactober Fest if nothing bad happens

Thank you

**Comment by Anurag-ak99** [comment]
if its still open please assign it to me
