### ISSUE TITLE
Makefile:8: recipe for target 'lint' failed Error: Process completed with exit code 2.

### ISSUE THREAD

**Issue by 0tist** [lukew3/mathgenerator#234]
Couldn't pass all the test, how do i correct this?

**Comment by shyamcody** [comment]
someone needs to go through the whole repo and correct all the lint issues; i.e. coding style not maintained in many places. There are around 400 errors currently in the lint action. If you want to contribute to this issue, open the details of why the lint fails. Then put the errors in full screen; go through each error and correct the style. lint follows flake-8 analysis rules, so if you search by error statement, you will find the solution very easily.

**Comment by 0tist** [comment]
@shyamcody could you please share the link on the same, maybe some reference, actually i've never done this, although my PR is merged but i wish to explore it further

**Comment by lukew3** [comment]
@shyamcody You should be able to just run the code through [autopep8](https://pypi.org/project/autopep8/) to fix it. I've just been hesitant to fix it because of all the changes that are taking place right now.

**Comment by lukew3** [comment]
Issues have been fixed
