### ISSUE TITLE
Vector dot product

### ISSUE THREAD

**Issue by midhunvarman** [lukew3/mathgenerator#240]
**Example Problem:** Evaluate dot product of two 3 dimensional vectors

**Example Solution:** let a = [-3 , 6, -2] and b = [-2 , 4, 0] return c = 30

**Further explanation:** Algebraically, the dot product is the sum of the products of the corresponding entries of the two sequences of numbers. Geometrically, it is the product of the Euclidean magnitudes of the two vectors and the cosine of the angle between them. These definitions are equivalent when using Cartesian coordinates.

**Would you like to be assigned to this:** Yes , I would like to work on this problem

**Comment by D-T-666** [comment]
Shouldn't `dot(a, b)` be `a.x*b.x + a.y*b.y + a.z+b.z`? So the answer in that example would be `30`?

**Comment by midhunvarman** [comment]
Yes , my bad

**Comment by helplessThor** [comment]
Can I get assigned?

**Comment by lonlander** [comment]
#239

**Comment by midhunvarman** [comment]
#239 added dot product
