### ISSUE TITLE
Want to add a function that converts angle in degree to radians

### ISSUE THREAD

**Issue by helplessThor** [lukew3/mathgenerator#250]
Want to add a function that converts an angle (in degrees) to angle in radians

For example, the angle 180 degree will be 3.14 radians, this is important in scientific computation.

I want to get assigned

**Comment by 0tist** [comment]
it would be great if u could convert radians to degrees as well

**Comment by trewest** [comment]
@helplessThor @0tist can you assign this issue to me? I can create two functions to convert degrees to radians and radians to degrees. Thanks

**Comment by helplessThor** [comment]
I'll create the two functions as required

**Comment by helplessThor** [comment]
@lukew3 please assign me so that i can add the two functions
