### ISSUE TITLE
Polar Form of Complex Numbers

### ISSUE THREAD

**Issue by ShivenTripathi** [lukew3/mathgenerator#251]
**Convert the complex number 1+i1 to Polar Form r*exp(i*theta)**

**Example Solution: 1.41exp(*ipi/4)**
//in the implementation, i*pi/4 would be reduced to i0.78
**Further explanation: r=sqrt(a**2+b**2), theta=atan(y/x) {there's some more conditions for the principal argument}  **

**Would you like to be assigned to this: Yes**

**Comment by helplessThor** [comment]
hey @adit098 dont do anything unless you are assigned
