### ISSUE TITLE
Decimal to Octal

### ISSUE THREAD

**Issue by Metropass** [lukew3/mathgenerator#252]
**Example Problem:**
Convert the value `256` into octal format
**Example Solution:**
Dec = 256
Oct = 0o400
**Further explanation:**
Converts a decimal value into it's octal counterpart
**Would you like to be assigned to this:**
Yes I would like to be assigned this

**Comment by Nitsujed** [comment]
Can I take this?

**Comment by Rishabrp99** [comment]
hey @Metropass Can you please assign it to me ?I  would love to contribute for the same.

**Comment by lukew3** [comment]
@Metropass Yeah, I think that this would be good
