### ISSUE TITLE
Move generator instances to their own module

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#258]
A couple of things have to be done for each generator instance:
* Add the line `from ..__init__ import Generator` to the second line of each file in the funcs folder with the exception of addition.py and __init__.py
* Copy the line that creates the generator instance from mathgen.py and put it at the bottom of the file that it corresponds to in the funcs folder. Remove the line from the mathgen.py file
* Rename the file to the name of the generator instance (with .py at the end)
* Change the line `from .moduleFunc import *` in `__init__.py` to fit the new name of the file

**Comment by NarayanAdithya** [comment]
is it from ". ."
Also can i help with this ?

**Comment by lukew3** [comment]
The first bullet point is correct. From `from ..__init__` imports the generator class from the init file in the mathgenerator folder outside of the funcs folder.

**Comment by lukew3** [comment]
I already did addition.py if you want an example of what it should look like.

**Comment by lukew3** [comment]
@NarayanAdithya If you are working on this, maybe submit a pr with just a couple first so that if there are any mistakes they can be corrected before the whole thing is done incorrectly.

**Comment by lukew3** [comment]
@NarayanAdithya I'm pretty much done with this on restructure2 branch. I didn't rename every file and have some bug that puts the first import last on the list of generators but everything else is complete.
