### ISSUE TITLE
Celsius to Fahrenheit

### ISSUE THREAD

**Issue by Nitsujed** [lukew3/mathgenerator#260]
Example Problem: F = (C x 9/5) +32

Example Solution: (0C x 9/5) + 32 = 32

Further explanation: Convert Celsius to Fahrenheit

Would you like to be assigned to this: yes

**Comment by Nitsujed** [comment]
@lukew3 Are you looking for conversions like this as well or just math formulas?

**Comment by lukew3** [comment]
This is good. Just make sure that it includes a question and answer. A problem could be 'convert x degrees celsius to degrees fehrenheit' and the solution might be 'y'

**Comment by helplessThor** [comment]
> This is good. Just make sure that it includes a question and answer. A problem could be 'convert x degrees celsius to degrees fehrenheit' and the solution might be 'y'

hey then why all the functions we are using based on random? we can do that like with individual inputs, isn't it?

**Comment by lukew3** [comment]
> hey then why all the functions we are using based on random? we can do that like with individual inputs, isn't it?

I'm not sure I understand your question completely. Users of the software should only have to say the name or id of the problem type they want to create and then set limits for how difficult they want it to be. This repo isn't a calculator, it's a random problem generator.
