### ISSUE TITLE
Add different support to quadratic solver

### ISSUE THREAD

**Issue by strikeraryu** [lukew3/mathgenerator#275]
**Name or Id of generator:**
50
**Issue:**
need support like solutions in simplified form and general form, imaginary roots

**Comment by helplessThor** [comment]
can you give some example?

**Comment by strikeraryu** [comment]
soln support
general solution 
(1 + sqrt(3))/2, (1 - sqrt(3))/2
simplified solution
1.3660, -0.3660

question with imaginary roots 
x^2 - 2x + 5
roots
(2 + 4i)/2, (2 - 4i)/2

**Comment by lukew3** [comment]
I'd just like to mention that id 21 exists as well, which generates problems with whole number solutions. The general solution could be added on to id 50 as a parameter for rounded or exact answers. Problems with imaginary roots should be a seperate generator.

**Comment by strikeraryu** [comment]
I just checked that in that the quadratic question will be simple so it can be factorized. It doesn't support the question which needs a quadratic formula to solve. 
I was thinking to give a generalized solution Because a few questions are difficult to simplify so the person using this library wants to check the solution in a generalized form.
I can make a new generator complex quadratic generator with this support. should I do that?

**Comment by strikeraryu** [comment]
should I close this issue and make a new issue with a different template for the new generator idea. @lukew3

**Comment by lukew3** [comment]
@strikeraryu Yes

**Comment by helplessThor** [comment]
@lukew3 please add hacktoberfest accepted label in the merged pull request of angle conversion between degrees and radians
