### ISSUE TITLE
Perimeter of a Polygon

### ISSUE THREAD

**Issue by Metropass** [lukew3/mathgenerator#278]
**Example Problem:**
What's the perimeter of a polygon with 4 sides that has the length (10,10,20,20)?
**Example Solution:**
`perimeter_polygon()` = `60`
**Further explanation:**
Calculates the perimeter of a polygon that has `n` sides
**Would you like to be assigned to this:**
Yes, I would like to be assigned this

**Comment by lukew3** [comment]
This looks good.
