### ISSUE TITLE
Wind Chill Calculator

### ISSUE THREAD

**Issue by Metropass** [lukew3/mathgenerator#279]
**Example Problem:**
The current temperature is 9°C, and the Wind is blowing 13km/h, what's the wind chill temperature?
**Example Solution:**
`wind_chill(9,13)` = `It will feel like 7°C`
**Further explanation:**
During a cold day (usually in Winter), the temperature felt by the body is typically lower than the actual air temperature. This is known as Wind Chill
**Would you like to be assigned to this:**
Yes, I would like to be assigned this.

**Comment by misterdabu** [comment]
Yes, I would like to be assigned this.

**Comment by lukew3** [comment]
This doesn't seem like a problem that would fit the goals of the project. It isn't something typically taught in school.
