### ISSUE TITLE
getGenList broken

### ISSUE THREAD

**Issue by D-T-666** [lukew3/mathgenerator#286]
for some reason, genList doesn't get filled up with generators, and thus getGenList is broken (returning an empty list).
when this get's fixed, I will make makeReadme.py function properly.

**Comment by lukew3** [comment]
I tried makeReadme.py and it looks like getGenList is working but there is an error with getting the function names of the generators because mathGen.py no longer declares the generator instances.

**Comment by lukew3** [comment]
I'll fix that right now.

**Comment by D-T-666** [comment]
no need
