### ISSUE TITLE
Probability of diesese given test result

### ISSUE THREAD

**Issue by Vhizux** [lukew3/mathgenerator#287]
**Example Problem:**
Someone tested positive for a nasty disease which only 0.41% of population have. Test sensitivity(true positive) is equal to SN= 90.15% whereas test specificity(true negative) SP= 95.01%. What is the probability that this guy really has that disease?
**Example Solution:**
6.93%
**Further explanation:**
It's kind of Bayesian problem for calculating conditional probability with test result as condition
More detailed explanation: https://www.youtube.com/watch?v=R13BD8qKeTg
**Would you like to be assigned to this:**
Yes

**Comment by PetitNigaud** [comment]
Hello there. I would give it a try! Seems quite relevant in these times...

**Comment by Vhizux** [comment]
Hi @lukew3. Are you interested in this generator? I'm waiting until you assign me to this

**Comment by lukew3** [comment]
I don't think it fits with the rest of the project. This isn't something generally taught in a math class.

**Comment by Vhizux** [comment]
Hi @lukew3. I thought that conditional probability is taught in school. I had this in my math classes. Which level of math classes are you targeting? This will help me with future ideas

**Comment by lukew3** [comment]
@Vhizux You make a good point. It's probably good. Just make sure you mention the math behind it in the generator name.

**Comment by Vhizux** [comment]
@lukew3 Got it!
