### ISSUE TITLE
Minutes to Hours

### ISSUE THREAD

**Issue by Metropass** [lukew3/mathgenerator#301]
**Example Problem:**
Convert 230 minutes to Hours&Minutes
**Example Solution:**
`minutes_to_hours(230) = 3h:50m`
**Further explanation (optional):**
This converts the time (in minutes) into the hour-minute format
**Would you like to be assigned to this:**
Yes, I would like to be assigned this

**Comment by Veguinho** [comment]
Yes, I would like to be assigned this
