### ISSUE TITLE
e() mathematical constant

### ISSUE THREAD

**Issue by niyonx** [lukew3/mathgenerator#302]
**Example Problem:**
Generate value of e from scratch

**Example Solution:**
e() returns 2.718281828459045

**Further explanation (optional):**
https://en.wikipedia.org/wiki/E_(mathematical_constant)

**Would you like to be assigned to this:**
Yes

**Comment by niyonx** [comment]
hey @lukew3 if you're looking to calculate the constant e from scratch you can assign me to it

**Comment by lukew3** [comment]
python's math module already has math.e built in.
