### ISSUE TITLE
pi() mathematical constant

### ISSUE THREAD

**Issue by niyonx** [lukew3/mathgenerator#303]
**Example Problem:**
Generate the value of pi from scratch

**Example Solution:**
pi() returns 3.141592653589793

**Further explanation (optional):**
https://en.wikipedia.org/wiki/Pi

**Would you like to be assigned to this:**
Yes

**Comment by niyonx** [comment]
hey @lukew3 if you're looking to calculate the constant pi from scratch you can assign me to it

**Comment by lukew3** [comment]
I don't think that's necessary. We should just use math.pi.
