### ISSUE TITLE
Calculate signum function of a number

### ISSUE THREAD

**Issue by gautamprasad73** [lukew3/mathgenerator#313]
**Example Problem:**
Signum function, f(x) = |x|/x. Ex- Find signum function value if x = -10. 
**Example Solution:**
-1
**Further explanation (optional):**
Basically, if x>0 then f(x) is 1, if x<0 then f(x) is -1 and if x=0 then f(x)=0
**Would you like to be assigned to this:**
yes

**Comment by sathyasub** [comment]
@Gautampd73 can you assign this to me

**Comment by gautamprasad73** [comment]
no , i am doing it. u can do greatest integer function

**Comment by RosNayak** [comment]
Hey, can you assign any mathematical function to me? @Gautampd73
