### ISSUE TITLE
Binomial distribution

### ISSUE THREAD

**Issue by Vhizux** [lukew3/mathgenerator#316]
**Example Problem:**
A manufacturer of metal pistons finds that, on average, 38.4% of the pistons they manufacture are rejected because they are incorrectly sized. What is the probability that a batch of 11 pistons will contain no more than 1 rejected pistons

**Example Solution:**
3.81%

**Further explanation (optional):**
crash course video about that topic: https://www.youtube.com/watch?v=WR0nMTr6uOo

**Would you like to be assigned to this:**
Yes

**Comment by Vhizux** [comment]
@lukew3 What do you think? This should be ok, right?

**Comment by lukew3** [comment]
Yeah, its good
