### ISSUE TITLE
Compare Fractions

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#34]
Example Problem:
Which symbol represents this relationship 3/2 O 5/6?
Example Solution:
\>

I don't really like how this problem is formatted but I like the concept. If you have a better idea of what the problem/solution should look like please comment below.

**Comment by ieshaan12** [comment]
In this, we're only considering relational operators, right?

**Comment by lukew3** [comment]
Yes, the solution should be >, <, or =

**Comment by ieshaan12** [comment]
Can you assign this to me @lukew3?

**Comment by aniruddhav25** [comment]
I suggest to rephrase the problem as:-
Which symbol represents the comparison between 3/2 O 5/6?
as the word relationship seems to be vague to get the answers as >, <, or =.

If you like this suggestion,I would like to get assigned to this task and contribute to it @lukew3

**Comment by lukew3** [comment]
Okay, I like that. If you phrase it like that it might make sense to put "and" in between the fractions instead of the "O".

**Comment by aniruddhav25** [comment]
Should I display the operators >,< and = in a pair of braces along with the question?
@lukew3 

For e.g.Which symbol represents the comparison between 3/2 and 5/6?(>,< or =)
