### ISSUE TITLE
Coefficient of n/n, intersection_of_two_lines

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#348]
**Name or Id of generator:**
algebra/intersection_of_two_lines, 41
**Issue:**
Coefficient is expressed as a fraction when it can be simplified to 1 and removed from the equation.
Question: Find the point of intersection of the two lines: y = 6/6x + 7 and y = 7/5x + 7
Answer: (0, 7)

**Comment by parthb83** [comment]
Hey @lukew3! I would like to work on this issue. Please guide me through what I have to do.

**Comment by parthb83** [comment]
Hey @lukew3, I was also thinking that when numerator in coefficient of x is 0, we could remove the x-term altogether. So if for example, given that, `y = 0/6x + 5`, it can be written as `y = 5`. Please provide your suggestion on this.

**Comment by lukew3** [comment]
> Hey @lukew3, I was also thinking that when numerator in coefficient of x is 0, we could remove the x-term altogether. So if for example, given that, `y = 0/6x + 5`, it can be written as `y = 5`. Please provide your suggestion on this.

I agree

**Comment by parthb83** [comment]
Hey please review the PR: #373.
