### ISSUE TITLE
Multiply 2x2 Matrice by Integer

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#35]
Example Problem:
3*[[5,0],[1,3]]=
Example Solution:
[[15,0],[3,9]]

The matrice [[5,0],[1,3]] looks like this:
| 5 , 0 |
| 1 , 3 |

**Comment by lukew3** [comment]
Problems like these should be formatted with asciimath when they are visualized.

**Comment by ieshaan12** [comment]
Can you assign this to me? I'll do it.

**Comment by ieshaan12** [comment]
#57 Close
