### ISSUE TITLE
Scientific Notation, Conics problems

### ISSUE THREAD

**Issue by skruglov2023** [lukew3/mathgenerator#350]
**Example Problem:**
1.45x10^5*3.21x10^-7
**Example Solution:**
4.6545x10^-2
**Further explanation (optional):**
**Conics problems**
parabola, circle, ellipse, hyperbola equations

**Would you like to be assigned to this:**
No

**Comment by jsun1590** [comment]
I would like to add the scientific notation problems generator if possible. Thanks!
