### ISSUE TITLE
Find Percentage Error if True and Observed Values are given

### ISSUE THREAD

**Issue by Sankari-K** [lukew3/mathgenerator#355]
Given the True value and the Observed value, calculate the percentage error.

**Example Problem:**
V true = 100
V observed = 105

**Example Solution:**
Percentage error is 5 %

**Further Explanation:**
Percentage error will be `((abs(V true - V observed))/abs(V true))*100`

**Would you like to be assigned to this:**
Yes, would love to contribute!

**Comment by lukew3** [comment]
I like it! Could also do a separate generator for percent difference using the formula: `2*abs(a-b)/(a+b)*100`.

**Comment by Sankari-K** [comment]
I've made a PR : #360
