### ISSUE TITLE
Redesigning of web page

### ISSUE THREAD

**Issue by Tanmay-901** [lukew3/mathgenerator#357]
# Issue:- 
On the website [Mathgenerator](https://lukew3.com/mathgenerator), the list of available generators needs a different location than a static list going simply down, which causes the user to go up and down the page a lot of times in case using multiple generators.  
## Suggestions:-  
* A multiple-column web page with a standalone scrollable available generator list 
* and the generator available on the other side which would be a lot handier.  

> Just a suggestion, as a user. Would love to work on the same if the maintainer(s) approve and assign.  

Thanks and regards.
[Tanmay Khandelwal](github.com/Tanmay-901)

**Comment by lukew3** [comment]
Sure, I'd love some help there. I've published the current source code to the `gh-pages` branch, but feel free to deviate from the old code.

**Comment by Tanmay-901** [comment]
Thanks for assigning and providing the details.
