### ISSUE TITLE
Broken Area of Triangle

### ISSUE THREAD

**Issue by jsun1590** [lukew3/mathgenerator#359]
Hi, the area of triangle function is broken. Answers are not rounded and some answers are broken.

### Example
**Input** 
a = 15
b = 1
c = 20

**Output**
(2.623718239906474e-15+42.8485705712571j)

I would like to be assigned if possible.

Thanks.

EDIT:
Upon further inspection, the issue arose because the generated sides cannot actually make a valid triangle, such that every side has to be smaller than the sum of the other 2 sides.

**Comment by lukew3** [comment]
Good catch! I've assigned the issue to you.
