### ISSUE TITLE
Calculate sum of Geometric Progression (G.P.)

### ISSUE THREAD

**Issue by divyansh1110** [lukew3/mathgenerator#364]
the script will calculate the sum of n terms of AP

I would like to add  the script for the above 

Thanks

**Comment by lukew3** [comment]
Already exists https://github.com/lukew3/mathgenerator/blob/main/mathgenerator/funcs/misc/geometric_progression.py. If you want to check if a generator exists, search in page with `ctrl`+`f` on the README/home page.
