### ISSUE TITLE
Able to Scroll to Top when a generator is clicked.

### ISSUE THREAD

**Issue by kaartik2611** [lukew3/mathgenerator#368]

**Comment by jsun1590** [comment]
I think this issue was raised in #357, but the assignee hasn't made a PR yet. I think it might be better to put the generator off to the side in a separate column from the list of generators just so the user can quickly switch between the generators without having to scroll back down again?

**Comment by kaartik2611** [comment]
I could try working on that..
But couldn't find the front end code for the application...
I you could guide me through that 
then i might solve this issue

**Comment by lukew3** [comment]
@kaartik2611 Front end code is inside the gh-pages branch of this repo. To get a specific branch on your local machine, you can use `git checkout gh-pages` while inside the repo. You can then `git switch <branch>` to navigate between the `gh-pages` branch and the `main` branch

**Comment by Sankari-K** [comment]
@lukew3 Okay, thank you!
Did you mean to tag @kaartik2611 though?

**Comment by lukew3** [comment]
> @lukew3 Okay, thank you! Did you mean to tag @kaartik2611 though?

Haha, yeah. Not sure why it suggested you when I typed in kaartik's name. Just updated my reply

**Comment by jsun1590** [comment]
@lukew3 cross referencing #357, am I able to work on the website redesign if PR is not submitted within another few days or so?

**Comment by lukew3** [comment]
@jsun1590 Yeah, sure

**Comment by Tanmay-901** [comment]
@jsun1590 @lukew3 @kaartik2611 I apologize for not acting on the issue, had to deal with some stuff. However, am glad the suggestion was considered and it brought some value to UX, I've made a minor change to further enhance the ease of usage by applying the scrollbar to the list instead of the whole web page, kindly consider. #376
