### ISSUE TITLE
[Gen Idea]: Simplify square root

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#410]
### Example Problem

Simplify $\sqrt{128}$: 

### Example Solution

$8\sqrt{2}$

### Optional, Provide Further Explanation

Given a square root that contains a perfect square multiplied by another number, remove the perfect square and leave the remaining radical.

### Assign Yourself?

- [ ] I want to be assigned to implement this

**Comment by typhoons01** [comment]
I have written a working function. I added the file under the name simplify_square_roots_generator in the mathgenerator folder. Since this is the first time I am using github, please let me know if I have done something wrong, or if you need me to change something in the code. Hope the function is of use to you.

**Comment by typhoons01** [comment]
Also, the code I have written has been modified such that the only square root simplifications it produces have neither the perfect square, nor the radical part equal to 1. Please let me know if you would like me to not incorporate that, and just produce the result without thinking about whether the number has the radical or perfect square parts equal to 1.

**Comment by lukew3** [comment]
Thanks, but I don't see an open pull request. I see that you have made changes on your fork. Can you open a pr with the base being the main branch of lukew3/mathgenerator and the head being the branch of your fork that you made changes on? You can find more about opening a pr here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

> Also, the code I have written has been modified such that the only square root simplifications it produces have neither the perfect square, nor the radical part equal to 1.

I agree with the way you implemented it.

**Comment by typhoons01** [comment]
Oh. Oops. I just did that (I think?)
Also, just wanted to know if there were any other generators that needed to be built, as in incomplete ones.
