### ISSUE TITLE
Power Rule Differentiation

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#5]
Example Problem:
Find the derivative of 5x^4
Example Solution:
20x^3

**Comment by akashsara** [comment]
Hey, would you mind if I pick this up? What should the scope of it be? Should all problems be of the form nx^m? And what should the limits for n and m be?

**Comment by lukew3** [comment]
@akashsara It's kind of up to you. Right now, I'm thinking that there could be a randomly generated number of terms between 1 and 5 maybe and you have to use the power rule for each of the terms. However, if you want you could just do 1 term with the format nx^m that you described. I would use 10 for the max of n and m as that is what generally is used in those types of problems.
