### ISSUE TITLE
Area of a triangle from lengths of 3 sides (Heron's formula)

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#55]
Example Problem:
Find the area of a triangle with side lengths 3, 4, and 5.
Example Solution:
6

Side lengths should be less than 20.

**Comment by aditya9110** [comment]
@lukew3 can I get this done??

**Comment by lukew3** [comment]
@aditya9110 Sure, I added you as assignee

**Comment by aditya9110** [comment]
The file is to be stored inside mathgenerator folder?

**Comment by aditya9110** [comment]
Okie got it!!

**Comment by aditya9110** [comment]
@lukew3 
[Area of Triangle](https://github.com/Todarith/mathgenerator/pull/59) Done.
