### ISSUE TITLE
Find the third angle of a triangle when given the first two

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#56]
Example Problem:
A triangle has internal angles of 32 degrees, 63 degrees, and x degrees. Find the value of x.
Example Solution:
85

**Comment by aditya9110** [comment]
I would like to take this next

**Comment by aditya9110** [comment]
@lukew3 
[Third Angle of Triangle](https://github.com/Todarith/mathgenerator/pull/73)  Done!!
