### ISSUE TITLE
System of Equations (two variables)

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#67]
Example problem:
Find the solution to the following system of equations: x-7y = -11, 5x+2y=-18.
Example solution:
(-4, 1)

Problem should be generated backwards so that the solution is a set of integers, not fractions or decimals.

**Comment by RobertWetzler** [comment]
I think this could be solved using linear algebra, taking it to reduced echelon form

**Comment by lukew3** [comment]
@RobertWetzler That sounds fun. If you'd like to try I'll add you as assignee.

**Comment by RobertWetzler** [comment]
I'll hold off for now in case someone else wants to do it, I've got some other things I'm working on currently. Also, reduced echelon form may be overkill for a system of only two variables, not sure.

**Comment by lukew3** [comment]
Np, I should have asked before assigning you. There probably is a simpler way to do it.

**Comment by RobertWetzler** [comment]
Ok, I think I've come up with a good way of doing this. Please assign to me
