### ISSUE TITLE
Evaluate Trig Functions

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#69]
Example Problem:
What is the value of sin((2pi)/3)?
Example Solution:
sqrt(3)/2

Inside of trig function should be values found on unit circle. This includes pi/6, pi/4, pi/3, pi/2 and equivalents in other quadrants.

**Comment by lukew3** [comment]
Trig functions sin, cos, and tan should be randomly selected.

**Comment by ieshaan12** [comment]
Will we be taking only those specific angles or arbitrary values as well? And can we take degrees as arguments or only radians?

**Comment by ghost** [comment]
Trig Function is basically related to an angle of a right-angled triangle to ratios of two side lengths.Widely used trig functions are sine ,cosine,tangent.

**Comment by AceVikings** [comment]
Hey I would like to give this one a try. Also just to confirm we want our range to be between -2pi to 2pi right ?

**Comment by lukew3** [comment]
@akashjha011 Correct.
