### ISSUE TITLE
Find Points of Horizontal Tangent of Function

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#70]
Example Problem:
f(x)=x^3-3x
Example Solution:
(-1, 2), (1, -2)

**Comment by Riddhima-jain** [comment]
What should be the maximum order of the equation for random coefficients generation?

**Comment by Riddhima-jain** [comment]
What is the maximum number of variables that is to be taken into account?

**Comment by lukew3** [comment]
I'd say there should be a random number of terms of f(x) between 2 and 5 maybe. There should probably be a parameter for highest degree so that it can be made easier or more difficult.

**Comment by Luv8436** [comment]
Hii @lukew3  assign it to me , i am interested in coding this mathematical problem.

**Comment by y22-coding** [comment]
Hii @lukew3 assign it to me,i am interested in coding this mathematical problem.

**Comment by anupam54** [comment]
I am new in getting such task, can you explain the process to get this task because I can solve it.

**Comment by lukew3** [comment]
This is still open
