### ISSUE TITLE
Multiplication of complex numbers

### ISSUE THREAD

**Issue by ieshaan12** [lukew3/mathgenerator#75]
Problem: 3+2i, 1-i
Solution: 5-i
Range for Real and Imaginary numbers between -20, 20

**Comment by razinc** [comment]
Is this open to grab? I would like to try it, please.

**Comment by lukew3** [comment]
Yep, I've assigned you.

**Comment by razinc** [comment]
Thanks, my code is ready but if it is okay, may I ask a question? Why do we need the `Generator` class?

**Comment by ieshaan12** [comment]
@razinc shouldn't you show it's on the argand plane or something like i(iota)?

**Comment by razinc** [comment]
Hi @ieshaan12,

Sorry, I don't quite catch you. Are you talking about output of the `Generator`:
`25 Multiplication of 2 complex numbers (x + j) (y + j) =  xy + xj + yj -1`

or output of the `multiplyComplexNumbersFunc()`?
`('11j * (8+16j) = ', (-176+88j))`

Or should I plot both on a plane?

Thanks.

**Comment by ieshaan12** [comment]
Yeah, more like the second one @razinc

**Comment by lukew3** [comment]
> Why do we need the `Generator` class?

@razinc The generator class is able to hold the properties of a generator such as Title and Id. It makes it a lot easier to manage generators if each generator takes up one line. Class instances are added to genList which makes it super easy to get a generator by Id. I originally didn't have it but realized that creating a class is necessary for management and also adds possibilities for methods to be created.

**Comment by razinc** [comment]
Hi @ieshaan12. I feel like it would be easier to plot if I import numpy & matplotlib. Is that okay?

**Comment by ieshaan12** [comment]
@lukew3 Suggestions?

**Comment by lukew3** [comment]
@ieshaan12 I don't know why the plotting is necessary. However, the extent of my experience with imaginary numbers is limited. Currently, there is no way to include a graph in the problem/solution. If it is necessary to check existence of imaginary numbers with numpy or matplotlib it would be fine to import them.

**Comment by lukew3** [comment]
I do plan on making some sort of raw/custom output for parts of problems and solutions that cannot be accurately represented as just a string.

**Comment by razinc** [comment]
Hi @ieshaan12, should we continue with the plot, or do we wait for @lukew3 to implement his custom output?

**Comment by ieshaan12** [comment]
Like @lukew3 said, we don't have a way to do the plot thing.
@razinc I think the best output would be of this format: `('11j * (8+16j) = ', (-176+88j))`

**Comment by pretam591** [comment]
Can I contribute as well, please?

**Comment by pretam591** [comment]
Would you assign it me, so that I can give a try..?

**Comment by razinc** [comment]
> > Why do we need the `Generator` class?
> 
> @razinc The generator class is able to hold the properties of a generator such as Title and Id. It makes it a lot easier to manage generators if each generator takes up one line. Class instances are added to genList which makes it super easy to get a generator by Id. I originally didn't have it but realized that creating a class is necessary for management and also adds possibilities for methods to be created.

Thanks @lukew3 for your explanation.
