### ISSUE TITLE
Generation of docstrings

### ISSUE THREAD

**Issue by ieshaan12** [lukew3/mathgenerator#77]
The idea is to generate docstrings for each and every function which can be returned by the generator class using `help {generatorName}` by adding a __doc__ to Generator class. This will assist those who use this library.

**Comment by ieshaan12** [comment]
We can decide on a particular format of docstrings.

**Comment by lukew3** [comment]
This would be nice, but I feel like it would take a lot more effort than it's worth. I created the generator example problem and solution parameter and README.md table column so that devs could understand what would be outputted when the function was run.

**Comment by ieshaan12** [comment]
Yeah, I understand that, but this is for people who wish to use the library, in contrast to those developing it.
