### ISSUE TITLE
Find the HCF of two numbers

### ISSUE THREAD

**Issue by mayanknegi-kun** [lukew3/mathgenerator#85]
Problem - Two numbers are given ,example 36 and 23 and we have to find their highest common factor.

Solution - The HCF of 36 and 24 is 12

**Comment by lukew3** [comment]
We already have an implementation of gcd which is the same thing as hcf.

**Comment by lukew3** [comment]
Maybe a new instance should be created with the same function call.

**Comment by lukew3** [comment]
Nevermind my previous 2 comments. A seperate function and class instance for HCF would be better than trying to integrate it with gcd.

**Comment by mayanknegi-kun** [comment]
I'll make a new instance then
