### ISSUE TITLE
Adding a function to find factorial of a number

### ISSUE THREAD

**Issue by deepampriyadarshi** [lukew3/mathgenerator#87]
## Problem
   Find the factorial of an integer i.
## Solution
Creating a recursive function fact(int i) that returns factorial of.
## Advantage 
Function fact(int i) can also used for creating function for permutation and combination

**Comment by deepampriyadarshi** [comment]
Hi @lukew3 i want to add this feature... Please assign me for this..

**Comment by lukew3** [comment]
@deepampriyadarshi Python math module already has a factorial method. You just need to add `import math` and run the function with `math.factorial(num)`

**Comment by deepampriyadarshi** [comment]
@lukew3 actually i got confused with the objective of the repo... :-) we can close this issue if you want
