### ISSUE TITLE
Total Number of Combinations

### ISSUE THREAD

**Issue by Ritu1611** [lukew3/mathgenerator#91]
I want to add the function that gives number of combinations for picking **x** objects at a time from **y** different objects.

Sample problem:- Number of combinations for picking 4 objects at a time from 6 objects.
Solutions:- There are 15 different combinations available.

**Comment by lukew3** [comment]
Good idea, I've assigned it to you.

**Comment by lukew3** [comment]
@Ritu1611 There should also be a permutations problem generator. Would you like to pick that up as well or should I add it as an issue for somebody else?

**Comment by Ritu1611** [comment]
I will do that. I was thinking to link this with probability problems. I have already added the function and a pull request can you see that.

**Comment by Ritu1611** [comment]
@lukew3  I am new to this. Can you tell me whether I am done with this combinations function or else I have to do something more.

**Comment by lukew3** [comment]
Sorry, I just forgot to close the issue. Your combinations pr was good.
