### ISSUE TITLE
Surface area and volume of different 3D figures

### ISSUE THREAD

**Issue by ieshaan12** [lukew3/mathgenerator#94]
Cylinder, Cube, Cubiod, Cone and so on.
@lukew3 Can you assign this to me, I'd like to work on this?

**Comment by ieshaan12** [comment]
@lukew3 Can we add math as a dependency? We'll need to use math.pi and math.sqrt for geometry related stuff eventually.
For now, I put a global variable as PI = 3.1416, but should we just import math for it?

**Comment by lukew3** [comment]
Yeah, sure. It's necessary for this project.
