### ISSUE TITLE
Quadratic equation

### ISSUE THREAD

**Issue by ShivenTripathi** [lukew3/mathgenerator#96]
would be easy to build a generator to solve for ax^2+bx+c=0, maybe phrase it like some operation on its roots.

**Comment by lukew3** [comment]
Okay, so a problem would be something like: 
Solve for x^2-8x+5 using the quadratic formula.
And the solution would be:
x=7.32, x=0.68
OR 
x=4+-sqrt(11)

**Comment by ShivenTripathi** [comment]
yeah, could have solutions as x= x1,x2
where x1, x2 are roots truncated to second decimal

**Comment by lukew3** [comment]
Okay, do you want me to assign you this?

**Comment by ShivenTripathi** [comment]
sure, i'll have it ready in a while

**Comment by cardboardboxpepe** [comment]
Can I contribute?

**Comment by ak6jackpot** [comment]
I can add the functionality of finding range of the quadratic equation.

**Comment by strikeraryu** [comment]
I like to add different support in this like giving solutions both in a generalized form and simplified form.
Allow users to opt for questions with imaginary roots.

**Comment by ShivenTripathi** [comment]
@lukew3 do you want me to update the README also for this generator?

**Comment by ShivenTripathi** [comment]
@ak6jackpot @strikeraryu i think both are good ideas but would be better implemented as separate generators so you might want to open another issue for that.
This also highlights a point for restructuring the project as simply creating new generators all the time would make this hard to maintain
