### ISSUE TITLE
Trigonometric Values of Standard Angles.

### ISSUE THREAD

**Issue by aniruddhav25** [lukew3/mathgenerator#97]
I want to add the function that gives Sine,Cosine,Tangent of only the standard Angles which includes 0,30,45,60 & 90 degrees.

Sample problem:- What is the Sin(30)?
Solutions:- 1/2

Just a basic idea of the function.Can add the remaining functions too if required.

**Comment by lukew3** [comment]
Okay, sure. This is similar to #69 which hasn't been implemented yet.

**Comment by helplessThor** [comment]
I want to add the ability to pass angles as radian

**Comment by aniruddhav25** [comment]
@lukew3 What should be displayed for tan(90)?  ∞ or undefined?

**Comment by ak6jackpot** [comment]
> @lukew3 What should be displayed for tan(90)? ∞ or undefined?

I think it will be infinite, simply because tan is opp side/adj side and when the angle is 90, adj side is 0. It's not undefined, it's just infinite

**Comment by ak6jackpot** [comment]
I want to add secant, cosecant, cotangent for a start.

**Comment by ak6jackpot** [comment]
also, given the function value, can give the resulting angle

**Comment by aniruddhav25** [comment]
@lukew3 closing this issue.
@ak6jackpot you can raise a new issue for your additions.
