### ISSUE TITLE
Simple Interest Calculation

### ISSUE THREAD

**Issue by deepampriyadarshi** [lukew3/mathgenerator#98]
## Sample problem 
Given principle amount is Rs.1000, rate of interest 5% and time period is 5 years. Calculate the simple interest.
## Solution
SI = (p * r * t)/100 = 250

**Comment by deepampriyadarshi** [comment]
@lukew3 please assign me for this...

**Comment by lukew3** [comment]
There should be a parameter for currency type. Students from other countries might be confused if they see a currency they are not familiar with.

**Comment by deepampriyadarshi** [comment]
> There should be a parameter for currency type. Students from other countries might be confused if they see a currency they are not familiar with.

Nice point Dude... So should i use USD which is the international mode of currency exchange?

**Comment by lukew3** [comment]
You could say dollars. A lot of countries call their countries currency the dollar and if the country doesn't use dollars, they can probably assume that it is usd, which is recognized worldwide.
