### ISSUE TITLE
Project Restructure

### ISSUE THREAD

**Issue by lukew3** [lukew3/mathgenerator#99]
This project has grown a lot and it seems like it is time for a new structure, better suited to the size of this project. I'm currently looking for ideas on how to better restructure this project. This comment will be edited as new ideas are proposed.
Current Ideas are:
* Place each generator into a seperate file. Organize files by type of problem.
* Group generators into class-level like Algebra, Calculus, or Geometry. Multiple generators are still stored in the same file.

Non-exclusive ideas:
* Make a module for common functions that might be used in multiple generators. Could be called `utils.py`.
* Consider adding docstrings to generator class so that users can understand what the generator does. See #77.

**Comment by akashsara** [comment]
I also wanted to add another thing - right now there's a couple of nested functions that are being used commonly. I think it would be better if we moved these to another file (Maybe something like `utils.py` so they can call `utils.gcd()`). 

But thinking a little bit more about this, it also makes sense to sort of isolate the actual operation from the generator. As a toy example of what I mean:

```
def add(x, y):
    return x+y

def additionFunc(<params_for_generator>)
    a = ...
    b = ...
    problem = f"{a}+{b}="
    solution = str(add(a,b))
    return problem, solution
```

I think this makes more sense as this being math, there's a lot of operations that build on each other and are used by other operations. 

What do you think?

**Comment by ieshaan12** [comment]
@akashsara I agree with the general idea of it, but I don't think we need to create separate functions for stuff like add, sub, mul, div, exp, log etc since there are already functions to do that.

**Comment by akashsara** [comment]
> 
> 
> @akashsara I agree with the general idea of it, but I don't think we need to create separate functions for stuff like add, sub, mul, div, exp, log etc since there are already functions to do that.

Ah no that was just a toy example. We won't need to do this with things that are just one liners. As a real example, I see a gcd function defined a couple of times. That could be moved out.

**Comment by 0tist** [comment]
we can have separation of the data on the basis of the type of the data that function uses, lets say we can have a folder for scalars and can have different classes for different types of classes, For example: 
mathgenerator->scalars->Algerbra->addition

**Comment by ieshaan12** [comment]
@lukew3 
Could we organise certain categories and then divide them?
Just giving examples, Arithmetic, Geometry, Algebra, Trignometry?

**Comment by razinc** [comment]
> @lukew3
> Could we organise certain categories and then divide them?
> Just giving examples, Arithmetic, Geometry, Algebra, Trignometry?

Hi @lukew3, I think this will be super helpful. Maybe we can create a switch if user want to create questions only on certain topics?

**Comment by lukew3** [comment]
This is in progress in the restructure branch

**Comment by lukew3** [comment]
One useful util function could be organizing a polynomial into the order of decreasing exponents.
